-- Phase 4D READ-ONLY preflight. Review before migration.
SELECT DATABASE() selected_database,CASE WHEN DATABASE()='u676721746_essivery' THEN 'PASS' ELSE 'FAIL - WRONG DATABASE' END database_check;
SELECT expected.table_name,CASE WHEN actual.table_name IS NULL THEN 'MISSING - migration may create' ELSE 'EXISTS - inspect' END table_state FROM (SELECT 'partners' table_name UNION ALL SELECT 'partner_business_modules' UNION ALL SELECT 'restaurants' UNION ALL SELECT 'cuisines' UNION ALL SELECT 'restaurant_cuisines' UNION ALL SELECT 'partner_onboarding_applications' UNION ALL SELECT 'partner_onboarding_steps' UNION ALL SELECT 'schema_migrations') expected LEFT JOIN information_schema.tables actual ON actual.table_schema='u676721746_essivery' AND actual.table_name=expected.table_name ORDER BY expected.table_name;
SELECT table_name,column_name,column_type,is_nullable,column_default,extra,ordinal_position FROM information_schema.columns WHERE table_schema='u676721746_essivery' AND table_name IN('restaurants','cuisines','restaurant_cuisines','partner_business_modules') ORDER BY table_name,ordinal_position;
SELECT table_name,index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index) columns_list FROM information_schema.statistics WHERE table_schema='u676721746_essivery' AND table_name IN('restaurants','restaurant_cuisines','partner_business_modules') GROUP BY table_name,index_name,non_unique ORDER BY table_name,index_name;
SET @q=IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='u676721746_essivery' AND table_name='restaurants')=1,'SELECT owner_user_id,COUNT(*) duplicate_count FROM `u676721746_essivery`.`restaurants` WHERE owner_user_id IS NOT NULL AND deleted_at IS NULL GROUP BY owner_user_id HAVING COUNT(*)>1','SELECT ''restaurants missing; migration will create it'' preflight_note');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q=IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='u676721746_essivery' AND table_name='restaurant_cuisines')=1,'SELECT restaurant_id,cuisine_id,COUNT(*) duplicate_count FROM `u676721746_essivery`.`restaurant_cuisines` GROUP BY restaurant_id,cuisine_id HAVING COUNT(*)>1','SELECT ''restaurant_cuisines missing; migration will create it'' preflight_note');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q=IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='u676721746_essivery' AND table_name='cuisines')=1,'SELECT id,public_id,name,slug,status FROM `u676721746_essivery`.`cuisines` ORDER BY name','SELECT ''cuisines missing - STOP; no master seed is included'' preflight_note');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q=IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='u676721746_essivery' AND table_name='restaurants')=1,'SHOW CREATE TABLE `u676721746_essivery`.`restaurants`','SELECT ''restaurants missing'' preflight_note');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q=IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='u676721746_essivery' AND table_name='cuisines')=1,'SHOW CREATE TABLE `u676721746_essivery`.`cuisines`','SELECT ''cuisines missing - STOP'' preflight_note');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
SET @q=IF((SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='u676721746_essivery' AND table_name='restaurant_cuisines')=1,'SHOW CREATE TABLE `u676721746_essivery`.`restaurant_cuisines`','SELECT ''restaurant_cuisines missing'' preflight_note');PREPARE s FROM @q;EXECUTE s;DEALLOCATE PREPARE s;
