<?php
declare(strict_types=1);
namespace Essivery\Partner\Services;
use Essivery\Api\Core\ApiException;use Essivery\Partner\Domain\PartnerContext;use Essivery\Partner\Repositories\PartnerDeliveryRepository;use Essivery\Partner\Repositories\PartnerDocumentRepository;use PDO;use Throwable;
final class PartnerDeliveryService
{
 private const OWNERSHIP=['OWNED','FAMILY','RENTED','COMPANY_PROVIDED'];
 public function __construct(private PDO$pdo,private PartnerDeliveryRepository$delivery,private PartnerDocumentRepository$documents,private PartnerSetupService$setup){}
 public function get(PartnerContext$c):array{$this->applicable($c);return$this->state($c,true);}
 public function update(PartnerContext$c,array$input,?callable$audit=null):array
 {
  $this->applicable($c);$type=strtolower(trim((string)($input['vehicleType']??'')));$ownership=strtoupper(trim((string)($input['vehicleOwnership']??'')));$confirmed=$input['confirmed']??null;$fields=[];$option=$type!==''?$this->delivery->option($type):[];if(!$option)$fields['vehicleType']='Choose an active vehicle type.';if(!in_array($ownership,self::OWNERSHIP,true))$fields['vehicleOwnership']='Choose a valid vehicle ownership type.';if(!is_bool($confirmed))$fields['confirmed']='Confirmation must be true or false.';$registration=$this->registration((string)($input['vehicleRegistrationNumber']??''));if($option&&$this->flag($option,'requires_registration')){if($registration==='')$fields['vehicleRegistrationNumber']='Vehicle Registration Number is required for this vehicle.';elseif(!$this->validRegistration($registration))$fields['vehicleRegistrationNumber']='Enter a valid Indian vehicle registration number.';}elseif($registration!==''&&!$this->validRegistration($registration))$fields['vehicleRegistrationNumber']='Enter a valid Indian vehicle registration number.';if($fields)throw new ApiException(422,'VALIDATION_ERROR','Delivery Partner Setup validation failed.','Review your delivery vehicle details.',$fields);
  $this->pdo->beginTransaction();try{$before=$this->delivery->vehicle($c,true);$this->delivery->save($c,$type,$registration?:null,$ownership,$confirmed);$result=$this->state($c,true);if($audit)$audit(['vehicleType'=>$type,'vehicleOwnership'=>$ownership,'registrationPresent'=>$registration!=='','vehicleChanged'=>($before['vehicle_type']??null)!==$type,'completed'=>$result['step']['status']==='complete']);$this->pdo->commit();return$result;}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}
 }
 private function state(PartnerContext$c,bool$sync):array
 {
  $row=$this->delivery->vehicle($c,false);$options=$this->delivery->options();$option=[];foreach($options as$x)if($x['code']===($row['vehicle_type']??null))$option=$x;$requirements=$this->requirements($option,$this->documents->current($c));$confirmed=!empty($row['setup_confirmed_at']);$complete=!empty($row['vehicle_id'])&&$confirmed&&$requirements['allRequiredPresent'];$correction=$requirements['hasCorrection'];$setup=$sync&&!empty($row['vehicle_id'])?$this->setup->syncDeliveryState($c,$complete,$correction):$this->setup->load($c);
  return['delivery'=>['partnerName'=>$row['name']??'','vehicle'=>['type'=>$option?['code'=>$option['code'],'name'=>$option['name']]:null,'registrationNumber'=>$row['registration_number']??null,'ownership'=>$row['vehicle_ownership']??null],'documents'=>$requirements['documents'],'confirmed'=>$confirmed],'options'=>['vehicleTypes'=>array_map(fn($x)=>['code'=>$x['code'],'name'=>$x['name'],'requirements'=>$this->rule($x)],$options),'ownershipTypes'=>array_map(fn($x)=>['code'=>$x,'name'=>ucwords(strtolower(str_replace('_',' ',$x)))],self::OWNERSHIP)],'requirements'=>$option?$this->rule($option):['registrationRequired'=>false,'drivingLicenceRequired'=>false,'rcRequired'=>false,'insuranceRequired'=>false],'remainingRequirements'=>$this->remaining($row,$option,$requirements,$confirmed),'step'=>$this->step($setup),'setup'=>$setup];
 }
 private function requirements(array$option,array$rows):array{$by=[];foreach($rows as$row)$by[strtoupper((string)$row['document_type'])]=$row;$defs=[];if($option&&$this->flag($option,'requires_driving_licence'))$defs[]=['code'=>'DRIVING_LICENCE_FRONT','label'=>'Driving Licence','required'=>true];if($option&&$this->flag($option,'requires_rc'))$defs[]=['code'=>'VEHICLE_RC_FRONT','label'=>'Vehicle RC','required'=>true];if($option&&$this->flag($option,'requires_registration'))$defs[]=['code'=>'VEHICLE_INSURANCE','label'=>'Vehicle Insurance','required'=>$this->flag($option,'insurance_required')];$documents=[];$all=true;$correction=false;foreach($defs as$def){$row=$by[$def['code']]??null;$review=$row?$this->review((string)$row['review_status']):null;$counts=$row&&in_array($review,['pending','approved'],true);if($def['required']&&!$counts)$all=false;if($def['required']&&in_array($review,['needs_correction','rejected'],true))$correction=true;$documents[]=$def+['uploaded'=>(bool)$row,'reviewStatus'=>$review,'countsTowardCompletion'=>$counts,'document'=>$row?['reference'=>$row['public_id'],'fileType'=>str_ends_with(strtolower((string)$row['file_reference']),'.pdf')?'pdf':'image','uploadedAt'=>$row['created_at']?gmdate('c',strtotime((string)$row['created_at'])):null,'viewUrl'=>'/setup/documents/'.$row['public_id'].'/file']:null];}return['documents'=>$documents,'allRequiredPresent'=>$all,'hasCorrection'=>$correction];}
 private function remaining(array$row,array$option,array$requirements,bool$confirmed):array{$out=[];if(!$option)$out[]='vehicleType';elseif($this->flag($option,'requires_registration')&&empty($row['registration_number']))$out[]='vehicleRegistrationNumber';if(empty($row['vehicle_ownership']))$out[]='vehicleOwnership';foreach($requirements['documents']as$d)if($d['required']&&!$d['countsTowardCompletion'])$out[]=$d['code'];if(!$confirmed)$out[]='confirmation';return$out;}
 private function rule(array$x):array{return['registrationRequired'=>$this->flag($x,'requires_registration'),'drivingLicenceRequired'=>$this->flag($x,'requires_driving_licence'),'rcRequired'=>$this->flag($x,'requires_rc'),'insuranceRequired'=>$this->flag($x,'insurance_required')];}
 private function flag(array$x,string$key):bool{return(int)($x[$key]??0)===1;}
 private function registration(string$x):string{return strtoupper((string)preg_replace('/[\s-]+/','',trim($x)));}
 private function validRegistration(string$x):bool{return(bool)(preg_match('/^[A-Z]{2}[0-9]{1,2}[A-Z]{1,3}[0-9]{4}$/',$x)||preg_match('/^[0-9]{2}BH[0-9]{4}[A-Z]{1,2}$/',$x));}
 private function review(string$x):string{return match(strtolower($x)){'approved'=>'approved','rejected'=>'rejected','correction_required','needs_correction'=>'needs_correction',default=>'pending'};}
 private function applicable(PartnerContext$c):void{if($c->deliveryPartnerId===null||$c->identityType!=='delivery_partner'||$c->moduleCode!=='DELIVERY'||$c->businessPartnerId!==null)throw new ApiException(409,'PARTNER_SETUP_NOT_APPLICABLE','Delivery Partner Setup does not apply to this identity.','Delivery Partner Setup is not required for this Partner type.');}
 private function step(array$s):array{return array_values(array_filter($s['steps'],fn($x)=>$x['code']==='deliverySetup'))[0]??['code'=>'deliverySetup','status'=>'notStarted'];}
}
