<?php
declare(strict_types=1);
namespace Essivery\Partner\Services;
use Essivery\Api\Core\ApiException;use Essivery\Partner\Domain\PartnerContext;use Essivery\Partner\Repositories\PartnerRestaurantRepository;use PDO;use Throwable;
final class PartnerRestaurantService
{
 public function __construct(private PDO$p,private PartnerRestaurantRepository$r,private PartnerSetupService$s){}
 public function get(PartnerContext$c):array{$this->applicable($c);return$this->state($c);}
 public function update(PartnerContext$c,array$i,?callable$a=null):array{$this->applicable($c);$codes=$i['cuisines']??null;$mode=strtoupper(trim((string)($i['menuSetupMode']??'')));$f=[];if(!is_array($codes))$f['cuisines']='Select between 1 and 5 cuisines.';else{$codes=array_values(array_unique(array_map(fn($x)=>strtolower(trim((string)$x)),$codes)));if(count($codes)<1||count($codes)>5)$f['cuisines']='Select between 1 and 5 cuisines.';}if(!in_array($mode,['SELF','ASSISTED'],true))$f['menuSetupMode']='Choose how you want to prepare your menu.';if(($i['confirmed']??null)!==true)$f['confirmed']='Confirm the Restaurant details.';if($f)throw new ApiException(422,'VALIDATION_ERROR','Restaurant Setup validation failed.','Review your Restaurant Setup choices.',$f);$resolved=$this->r->resolveCuisines($codes);if(count($resolved)!==count($codes))throw new ApiException(422,'VALIDATION_ERROR','One or more cuisines are invalid.','Choose cuisines from the available list.',['cuisines'=>'Unknown or inactive cuisine selected.']);$this->p->beginTransaction();try{$before=$this->r->profile($c);$this->r->save($c,$mode,$resolved);$setup=$this->s->markRestaurantComplete($c);if($a)$a(['cuisineCodes'=>$codes,'cuisineCount'=>count($codes),'menuSetupMode'=>$mode,'modeChanged'=>($before['menu_setup_mode']??null)!==$mode]);$this->p->commit();return$this->project($this->r->profile($c),$this->r->options(),$setup);}catch(Throwable$e){if($this->p->inTransaction())$this->p->rollBack();throw$e;}}
 private function state(PartnerContext$c):array{return$this->project($this->r->profile($c),$this->r->options(),$this->s->load($c));}
 private function project(array$row,array$options,array$setup):array{return['restaurant'=>['businessName'=>$row['business_name']??'','identity'=>'restaurant','cuisines'=>array_map(fn($x)=>['code'=>$x['slug'],'name'=>$x['name']],$row['cuisines']??[]),'menuSetupMode'=>$row['menu_setup_mode']??null,'confirmed'=>!empty($row['setup_confirmed_at'])],'options'=>['cuisines'=>array_map(fn($x)=>['code'=>$x['slug'],'name'=>$x['name']],$options),'maximumCuisines'=>5],'step'=>$this->step($setup),'setup'=>$setup];}
 private function applicable(PartnerContext$c):void{if($c->deliveryPartnerId!==null||$c->identityType!=='restaurant'||$c->moduleCode!=='RESTAURANT')throw new ApiException(409,'PARTNER_SETUP_NOT_APPLICABLE','Restaurant Setup does not apply to this Partner identity.','Restaurant Setup is not required for this Partner type.');}
 private function step(array$s):array{return array_values(array_filter($s['steps'],fn($x)=>$x['code']==='restaurantSetup'))[0]??['code'=>'restaurantSetup','status'=>'notStarted'];}
}
