<?php
declare(strict_types=1);namespace Essivery\Partner\Services;
use Essivery\Api\Core\ApiException;use Essivery\Partner\Domain\PartnerContext;use Essivery\Partner\Repositories\PartnerReviewRepository;use PDO;use Throwable;
final class PartnerReviewService
{
 private const COMMON_DOCS=['AADHAAR_FRONT'=>'Aadhaar Front','AADHAAR_BACK'=>'Aadhaar Back','PAN'=>'PAN'];private const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 public function __construct(private PDO$pdo,private PartnerReviewRepository$r){}
 public function get(PartnerContext$c):array{$app=$this->r->application($c);if(!$app)throw new ApiException(409,'PARTNER_SETUP_NOT_INITIALIZED','Partner setup application is not initialized.','Business Setup is being prepared.');return$this->project($c,$app,$this->r->steps((int)$app['id']));}
 public function submit(PartnerContext$c,bool$confirmed,?callable$audit=null):array{if(!$confirmed)throw new ApiException(422,'VALIDATION_ERROR','Submission confirmation is required.','Confirm that your Partner profile information is correct.',['confirmed'=>'Confirmation is required.']);$this->pdo->beginTransaction();try{$app=$this->r->application($c,true);if(!$app)throw new ApiException(409,'PARTNER_SETUP_NOT_INITIALIZED','Partner setup application is not initialized.','Business Setup is being prepared.');if(in_array($app['application_status'],['submitted','under_review'],true)){$result=$this->project($c,$app,$this->r->steps((int)$app['id']));$this->pdo->commit();return$result;}if(in_array($app['application_status'],['approved','rejected'],true))throw new ApiException(409,'APPLICATION_READ_ONLY','This application can no longer be submitted.','Your application status is read-only.');$steps=$this->r->steps((int)$app['id']);$issues=$this->issues($steps);if($issues)throw new ApiException(409,'SETUP_INCOMPLETE','Required setup information is incomplete.','Complete or correct every required section before submitting.',[],false,['issues'=>$issues]);$type=$app['application_status']==='correction_required'?'resubmission':'submission';$this->r->submit($c,$app,$type);$updated=$this->r->application($c,false);if($audit)$audit(['applicationPublicId'=>$app['public_id'],'identityType'=>$c->identityType,'moduleCode'=>$c->moduleCode,'completionPercentage'=>100,'submissionType'=>$type]);$result=$this->project($c,$updated,$steps);$this->pdo->commit();return$result;}catch(Throwable$e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
 private function project(PartnerContext$c,array$app,array$steps):array{$stepMap=[];foreach($steps as$s)$stepMap[$s['step_code']]=$s;$issues=$this->issues($steps);$documentRows=$this->r->documents($c);$sections=[];$sections[]=$this->section('personal','Personal','/setup/personal',$stepMap,$this->personal($this->r->personal($c)));if($c->deliveryPartnerId===null){$sections[]=$this->section('business','Business','/setup/business',$stepMap,$this->r->business($c));}$sections[]=$this->section('location','Location','/setup/location',$stepMap,$this->r->location($c));if($c->deliveryPartnerId===null){$sections[]=$this->section('hours','Business Hours','/setup/hours',$stepMap,['schedule'=>$this->schedule($this->r->hours($c))]);$sections[]=$this->section('operations','Operations','/setup/operations',$stepMap,$this->operations($this->r->operations($c)));}$sections[]=$this->section('documents','Documents','/setup/documents',$stepMap,['items'=>$this->documents($c,$documentRows)]);$sections[]=$this->section('bank','Bank Details','/setup/bank',$stepMap,$this->bank($this->r->bank($c),$documentRows));$moduleCode=['RETAIL'=>'retail_setup','RESTAURANT'=>'restaurant_setup','HOME_SERVICE'=>'home_service_setup','DELIVERY'=>'delivery_setup'][$c->moduleCode];$sections[]=$this->section($moduleCode,$this->moduleTitle($c->moduleCode),'/setup/'.['RETAIL'=>'retail','RESTAURANT'=>'restaurant','HOME_SERVICE'=>'home-service','DELIVERY'=>'delivery'][$c->moduleCode],$stepMap,$this->module($c,$this->r->module($c)));$status=$this->status($app,$issues);$editable=in_array($app['application_status'],['draft','in_progress','correction_required'],true);$canSubmit=!$issues&&in_array($app['application_status'],['draft','in_progress','correction_required'],true);return['application'=>['publicId'=>$app['public_id'],'status'=>$status,'statusLabel'=>$this->label($status),'completionPercentage'=>(int)$app['completion_percentage'],'canSubmit'=>$canSubmit,'editable'=>$editable,'submittedAt'=>$app['submitted_at']?gmdate('c',strtotime($app['submitted_at'])):null,'version'=>(int)$app['version_no']],'identity'=>['type'=>$c->identityType,'module'=>$c->moduleCode],'sections'=>$sections,'issues'=>$issues,'nextAction'=>$this->action($status,$canSubmit)];}
 private function section(string$code,string$title,string$path,array$steps,array$data):array{$step=$steps[$code]??[];return['code'=>$code,'title'=>$title,'status'=>$this->camel((string)($step['step_status']??'not_started')),'editPath'=>$path,'data'=>$data];}
 private function issues(array$steps):array{$out=[];foreach($steps as$s)if((int)$s['is_required']===1&&$s['requirement_type']==='required'&&$s['step_status']!=='complete')$out[]=['stepCode'=>$this->camel($s['step_code']),'message'=>$s['step_status']==='needs_correction'?'This section needs correction.':'Complete this required section.','editPath'=>'/setup/'.$this->route($s['step_code'])];return$out;}
 private function personal(array$x):array{return['ownerName'=>$x['owner_name']??'','verifiedMobile'=>$x['mobile']??'','email'=>$x['email']??null];}
 private function bank(array$x,array$documents):array{$proof=null;foreach($documents as$document)if(strtoupper((string)$document['document_type'])==='BANK_PROOF'){$proof=['reference'=>$document['public_id'],'reviewStatus'=>$this->camel((string)$document['review_status']),'viewUrl'=>'/setup/documents/'.$document['public_id'].'/file'];break;}return['accountHolderName'=>$x['account_holder_name']??'','maskedAccountNumber'=>!empty($x['account_number_last4'])?'•••• '.$x['account_number_last4']:null,'ifsc'=>$x['ifsc_code']??null,'reviewStatus'=>$x['review_status']??null,'bankProof'=>$proof];}
 private function documents(PartnerContext$c,array$rows):array{$labels=self::COMMON_DOCS;if($c->deliveryPartnerId!==null)$labels+=['DRIVING_LICENCE_FRONT'=>'Driving Licence','VEHICLE_RC_FRONT'=>'Vehicle RC','VEHICLE_INSURANCE'=>'Vehicle Insurance'];$by=[];foreach($rows as$r)$by[$r['document_type']]=$r;$out=[];foreach($labels as$code=>$label){$r=$by[$code]??null;$out[]=['code'=>$code,'label'=>$label,'status'=>$r?$this->camel($r['review_status']):'missing','document'=>$r?['reference'=>$r['public_id'],'viewUrl'=>'/setup/documents/'.$r['public_id'].'/file']:null];}return$out;}
 private function schedule(array$rows):array{$by=[];foreach($rows as$r)$by[(int)$r['day_of_week']][]=$r;$out=[];foreach(self::DAYS as$i=>$day){$x=$by[$i]??[];if(!$x)$out[]=['day'=>$day,'summary'=>'Not configured'];elseif((int)$x[0]['is_closed'])$out[]=['day'=>$day,'summary'=>'Closed'];elseif((int)$x[0]['is_24_hours'])$out[]=['day'=>$day,'summary'=>'24 Hours'];else$out[]=['day'=>$day,'summary'=>implode(', ',array_map(fn($r)=>substr($r['opens_at'],0,5).'–'.substr($r['closes_at'],0,5).((int)$r['is_overnight']?' (overnight)':''),$x))];}return$out;}
 private function operations(array$x):array{return['essiveryDelivery'=>(bool)($x['essivery_delivery']??false),'selfDelivery'=>(bool)($x['self_delivery']??false),'customerPickup'=>(bool)($x['customer_pickup']??false),'serviceAtCustomerLocation'=>(bool)($x['service_at_customer_location']??false)];}
 private function module(PartnerContext$c,array$x):array{if($c->moduleCode==='RETAIL')return['category'=>$x['category_name']??null,'setupMode'=>$x['setup_mode']??null,'confirmed'=>!empty($x['confirmed_at'])];if(in_array($c->moduleCode,['RESTAURANT','HOME_SERVICE'],true))return['items'=>$x['items']??[],'setupMode'=>$x['setup_mode']??null,'confirmed'=>!empty($x['confirmed_at'])];return['vehicleType'=>$x['vehicle_name']??null,'registrationNumber'=>$x['registration_number']??$x['vehicle_number']??null,'ownership'=>$x['vehicle_ownership']??null,'confirmed'=>!empty($x['confirmed_at'])];}
 private function status(array$a,array$issues):string{$s=$a['application_status'];if($s==='approved')return'APPROVED';if($s==='rejected')return'REJECTED';if($s==='under_review')return'UNDER_REVIEW';if($s==='submitted')return'SUBMITTED';if($s==='correction_required')return'CORRECTION_REQUIRED';return$issues?'SETUP_INCOMPLETE':'READY_TO_SUBMIT';}
 private function label(string$s):string{return ucwords(strtolower(str_replace('_',' ',$s)));}private function action(string$s,bool$c):array{if($c)return['code'=>'SUBMIT','label'=>$s==='CORRECTION_REQUIRED'?'Review & Resubmit':'Submit for Review'];if(in_array($s,['SUBMITTED','UNDER_REVIEW'],true))return['code'=>'VIEW','label'=>'View Submission'];if($s==='CORRECTION_REQUIRED')return['code'=>'UPDATE','label'=>'Update Information'];return['code'=>'BACK','label'=>'Back to Setup Center'];}
 private function moduleTitle(string$m):string{return['RETAIL'=>'Retail Store Setup','RESTAURANT'=>'Restaurant Setup','HOME_SERVICE'=>'Home Service Setup','DELIVERY'=>'Delivery Partner Setup'][$m];}private function route(string$x):string{return['retail_setup'=>'retail','restaurant_setup'=>'restaurant','home_service_setup'=>'home-service','delivery_setup'=>'delivery'][$x]??str_replace('_','-',$x);}private function camel(string$x):string{return lcfirst(str_replace(' ','',ucwords(str_replace('_',' ',$x))));}
}
