import { ArrowLeft, CheckCircle2, ChevronRight, Eye, EyeOff, FileText, Image, Landmark, Loader2, Pencil, RefreshCw, ShieldCheck, Upload } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { returningToReview, setupExitPath } from '../utils/setupNavigation'

const EMPTY={accountHolderName:'',accountNumber:'',confirmAccountNumber:'',ifsc:''}
const MAX_PROOF_BYTES=5*1024*1024
export default function BankDetailsPage(){
  const navigate=useNavigate(),[state,setState]=useState(null),[form,setForm]=useState(EMPTY),[editing,setEditing]=useState(false),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[proofUploading,setProofUploading]=useState(false),[proofPreview,setProofPreview]=useState(''),[proofError,setProofError]=useState(''),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[success,setSuccess]=useState(false)
  useEffect(()=>{(async()=>{try{const result=await partnerSetupService.getBank();setState(result);setEditing(!result.bank.hasBankDetails);setForm({...EMPTY,accountHolderName:result.bank.accountHolderName||'',ifsc:result.bank.ifsc||''})}catch(e){setError(e?.response?.data?.error?.userMessage||'Bank details could not be loaded.')}finally{setLoading(false)}})()},[])
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty])
  useEffect(()=>{let cancelled=false,objectUrl='';const reference=state?.bankProof?.reference;if(!reference){setProofPreview('');setProofError('');return()=>{cancelled=true}};(async()=>{try{const blob=await partnerSetupService.getDocumentBlob(reference);if(cancelled)return;objectUrl=URL.createObjectURL(blob);setProofPreview(objectUrl);setProofError('')}catch{if(!cancelled){setProofPreview('');setProofError('The saved Bank proof could not be previewed. You can replace it below.')}}})();return()=>{cancelled=true;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[state?.bankProof?.reference])
  const change=(key,value)=>{setForm(current=>({...current,[key]:key==='ifsc'?value.toUpperCase():value}));setDirty(true);setFields(current=>({...current,[key]:undefined}));setError('')}
  const save=async e=>{e.preventDefault();setSaving(true);setError('');setFields({});try{const result=await partnerSetupService.saveBank(form);setState(result);setForm(EMPTY);setDirty(false);setEditing(false);setSuccess(true);if(returningToReview())navigate('/setup/review')}catch(err){const fieldErrors=err?.response?.data?.error?.fieldErrors||{};setFields(fieldErrors);setError(Object.values(fieldErrors)[0]||err?.response?.data?.error?.userMessage||"We couldn't save your Bank details.")}finally{setSaving(false)}}
  const edit=()=>{setForm({...EMPTY,accountHolderName:state.bank.accountHolderName||'',ifsc:state.bank.ifsc||''});setEditing(true);setSuccess(false)}
  const uploadProof=async file=>{if(!file)return;setProofError('');if(file.size>MAX_PROOF_BYTES){setProofError('File is too large. Maximum file size is 5 MB.');return}if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)){setProofError('Upload a JPEG, PNG, WebP or PDF file.');return}setProofUploading(true);try{await partnerSetupService.uploadBankProof(file);setSuccess(true);try{setState(await partnerSetupService.getBank())}catch{setProofError('Bank proof was saved, but the page could not refresh it. Reload the page to view it.')}}catch(err){setProofError(err?.response?.data?.error?.fieldErrors?.file||err?.response?.data?.error?.userMessage||"We couldn't upload the Bank proof.")}finally{setProofUploading(false)}}
  const continueSetup=()=>{const next=state?.setup?.steps?.find(step=>step.code===state.setup.nextRecommendedStep);navigate(next?`/setup/${next.routeCode}`:'/setup')}
  if(loading)return <div className="grid min-h-screen place-content-center gap-3 bg-slate-50 text-center"><Loader2 className="mx-auto animate-spin text-emerald-800"/><p>Loading Bank details…</p></div>
  return <div className="min-h-screen bg-[#f4f7f4] px-4 py-8 text-slate-950"><main className="mx-auto max-w-3xl"><button onClick={()=>dirty?confirm('Discard unsaved Bank details?')&&navigate(setupExitPath()):navigate(setupExitPath())} className="inline-flex items-center gap-2 text-sm font-black text-slate-600"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-7"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="mt-1 text-4xl font-black">Bank &amp; Payout Details</h1><p className="mt-2 text-slate-600">Add the bank account where you want to receive Essivery payouts.</p></header>
  {error&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</div>}
  {state?.bank?.hasBankDetails&&!editing?<Summary bank={state.bank} success={success} onEdit={edit}/>:<form onSubmit={save} className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6 flex items-center gap-3"><span className="rounded-2xl bg-emerald-100 p-3 text-emerald-900"><Landmark/></span><div><h2 className="text-xl font-black">{state?.bank?.hasBankDetails?'Replace Bank details':'Add Bank details'}</h2><p className="text-sm text-slate-500">Your full account number is never displayed after saving.</p></div></div><Field label="Account Holder Name" error={fields.accountHolderName}><input autoComplete="name" maxLength={150} value={form.accountHolderName} onChange={e=>change('accountHolderName',e.target.value)} className="input" required/></Field><Field label="Bank Account Number" error={fields.accountNumber}><Secret value={form.accountNumber} visible={show} onChange={v=>change('accountNumber',v)} toggle={()=>setShow(v=>!v)}/></Field><Field label="Confirm Bank Account Number" error={fields.confirmAccountNumber}><Secret value={form.confirmAccountNumber} visible={show} onChange={v=>change('confirmAccountNumber',v)} toggle={()=>setShow(v=>!v)}/></Field><Field label="IFSC Code" error={fields.ifsc}><input autoCapitalize="characters" maxLength={11} value={form.ifsc} onChange={e=>change('ifsc',e.target.value)} placeholder="HDFC0001234" className="input uppercase" required/></Field><div className="mt-5 flex gap-3"><button disabled={saving} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-900 px-5 py-3 font-black text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={18}/>:<ShieldCheck size={18}/>}Save Bank Details</button>{state?.bank?.hasBankDetails&&<button type="button" onClick={()=>{setEditing(false);setDirty(false);setForm(EMPTY)}} className="rounded-xl border border-slate-300 px-5 py-3 font-black">Cancel</button>}</div></form>}
  <BankProofCard proof={state?.bankProof} preview={proofPreview} error={proofError} uploading={proofUploading} onUpload={uploadProof}/>
  {state?.bank?.hasBankDetails&&!editing&&<div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-between"><button onClick={()=>navigate(setupExitPath())} className="rounded-xl border border-emerald-900 px-5 py-3 font-black text-emerald-900">Save &amp; Return</button><button disabled={state?.step?.status!=='complete'||proofUploading} onClick={continueSetup} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-900 px-5 py-3 font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Continue Setup<ChevronRight size={17}/></button></div>}
  {state?.bank?.hasBankDetails&&!editing&&state?.step?.status!=='complete'&&<p className="mt-3 text-right text-xs font-bold text-slate-500">Upload a valid Bank proof to complete this section.</p>}
  </main><style>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:.75rem;padding:.8rem 1rem;font-weight:700;outline:none}.input:focus{border-color:#047857;box-shadow:0 0 0 3px #d1fae5}`}</style></div>
}
function Field({label,error,children}){return <label className="mt-4 block"><span className="mb-2 block text-sm font-black">{label} *</span>{children}{error&&<span className="mt-1 block text-xs font-bold text-rose-700">{error}</span>}</label>}
function Secret({value,visible,onChange,toggle}){return <div className="relative"><input type={visible?'text':'password'} inputMode="numeric" autoComplete="off" value={value} onChange={e=>onChange(e.target.value.replace(/\s/g,''))} minLength={6} maxLength={20} className="input pr-12" required/><button type="button" aria-label={visible?'Hide account number':'Show account number'} onClick={toggle} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500">{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>}
function BankProofCard({proof,preview,error,uploading,onUpload}){const input=useRef(null),isPdf=proof?.fileType==='pdf',needsCorrection=['rejected','needs_correction'].includes(proof?.reviewStatus);return <section className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Required Bank proof</p><h2 className="mt-1 text-xl font-black">Cancelled cheque or passbook</h2><p className="mt-1 text-sm text-slate-500">Upload a clear image or PDF showing the account holder, account number and IFSC.</p></div>{proof?.uploaded?<span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-black text-sky-800">{needsCorrection?'Needs correction':proof.reviewStatus==='approved'?'Approved':'Pending verification'}</span>:<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">Not uploaded</span>}</div><div className="mt-5 grid min-h-44 place-items-center overflow-hidden rounded-2xl bg-slate-100">{preview&&!isPdf?<img src={preview} alt="Bank proof preview" className="h-44 w-full object-contain"/>:preview&&isPdf?<button type="button" onClick={()=>window.open(preview,'_blank','noopener,noreferrer')} className="grid place-items-center gap-2 p-5 font-black text-emerald-900"><FileText size={42}/>View PDF</button>:<div className="grid place-items-center gap-2 text-slate-400"><Image size={42}/><span className="text-sm font-bold">{proof?.uploaded?'Preview unavailable':'No Bank proof uploaded'}</span></div>}</div>{error&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">{error}</p>}{needsCorrection&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">Replace this proof with a clear, correct document.</p>}<input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event=>{onUpload(event.target.files?.[0]);event.target.value=''}}/><button type="button" disabled={uploading} onClick={()=>input.current?.click()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-900 px-4 py-3 font-black text-white disabled:opacity-50">{uploading?<Loader2 className="animate-spin" size={18}/>:proof?.uploaded?<RefreshCw size={18}/>:<Upload size={18}/>} {uploading?'Uploading…':proof?.uploaded?'Replace Bank Proof':'Upload Bank Proof'}</button><p className="mt-2 text-center text-xs font-bold text-slate-400">JPEG, PNG, WebP or PDF · maximum 5 MB</p></section>}
function Summary({bank,success,onEdit}){const status={pending:'Pending',approved:'Approved',rejected:'Rejected',needs_correction:'Needs correction'}[bank.reviewStatus]||'Pending';return <section className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm">{success&&<div className="mb-5 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 font-black text-emerald-900"><CheckCircle2 size={20}/>Bank details added</div>}<div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-slate-500">Account Holder</p><h2 className="text-2xl font-black">{bank.accountHolderName}</h2></div><button onClick={onEdit} className="inline-flex items-center gap-2 rounded-xl border border-emerald-900 px-4 py-2 text-sm font-black text-emerald-900"><Pencil size={15}/>Edit Bank Details</button></div><dl className="mt-6 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-3"><div><dt className="text-xs font-black uppercase text-slate-400">Account</dt><dd className="mt-1 font-black">Ending in {bank.last4}</dd></div><div><dt className="text-xs font-black uppercase text-slate-400">IFSC</dt><dd className="mt-1 font-black">{bank.ifsc}</dd></div><div><dt className="text-xs font-black uppercase text-slate-400">Verification</dt><dd className="mt-1 font-black">{status}</dd></div></dl>{['rejected','needs_correction'].includes(bank.reviewStatus)&&<p className="mt-4 rounded-xl bg-amber-50 p-3 font-bold text-amber-900">These details need correction. Select Edit Bank Details and submit the full account number again.</p>}</section>}
