import { ArrowLeft, Check, Clock3, Copy, Loader2, Minus, Moon, Plus, Save, Sun } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { returningToReview, setupExitPath } from '../utils/setupNavigation'

const dayNames=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
const suggested=()=>dayNames.map(day=>({day,closed:false,open24Hours:false,slots:[{opensAt:'09:00',closesAt:'21:00',overnight:false}]}))
const clone=value=>JSON.parse(JSON.stringify(value))

export default function BusinessHoursPage(){
  const navigate=useNavigate(),[days,setDays]=useState(suggested),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[saved,setSaved]=useState(false)
  useEffect(()=>{(async()=>{try{const data=await partnerSetupService.getHours();if(data.days?.length===7)setDays(data.days);setDirty(false)}catch(e){const code=e?.response?.data?.error?.code;if(code==='PARTNER_SETUP_NOT_APPLICABLE'){navigate(setupExitPath(),{replace:true});return}setError(e?.response?.data?.error?.userMessage||'Business Hours could not be loaded.')}finally{setLoading(false)}})()},[navigate])
  useEffect(()=>{const warn=event=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
  const totalSlots=useMemo(()=>days.reduce((sum,day)=>sum+(day.closed?0:day.open24Hours?1:day.slots.length),0),[days])
  const change=(index,recipe)=>{setDays(current=>{const next=clone(current);recipe(next[index],next);return next});setDirty(true);setSaved(false);setFields({})}
  const setMode=(index,mode)=>change(index,day=>{day.closed=mode==='closed';day.open24Hours=mode==='allDay';if(mode==='open'&&!day.slots.length)day.slots=[{opensAt:'09:00',closesAt:'21:00',overnight:false}];if(mode!=='open')day.slots=[]})
  const copyDay=(source,targets=dayNames)=>setDays(current=>{const next=clone(current),template=clone(next[source]);return next.map(day=>targets.includes(day.day)?{...clone(template),day:day.day}:day)}),markDirty=()=>{setDirty(true);setSaved(false);setFields({})}
  const applyCopy=(source,targets)=>{copyDay(source,targets);markDirty()}
  const save=async(destination)=>{setSaving(true);setError('');setFields({});try{const result=await partnerSetupService.saveHours({days});setDays(result.days);setDirty(false);setSaved(true);if(returningToReview()){navigate('/setup/review');return}if(destination==='dashboard')navigate('/dashboard');if(destination==='continue'){const next=result.setup?.steps?.find(step=>step.code===result.setup?.nextRecommendedStep);navigate(next?`/setup/${next.routeCode}`:'/setup')}}catch(e){setFields(e?.response?.data?.error?.fieldErrors||{});setError(e?.response?.data?.error?.userMessage||'Business Hours could not be saved.')}finally{setSaving(false)}}
  if(loading)return <Center><Loader2 className="animate-spin text-emerald-800"/><p>Loading Business Hours…</p></Center>
  return <div className="min-h-screen bg-[#f4f7f4] px-4 py-8 text-slate-950"><main className="mx-auto max-w-6xl"><button onClick={()=>navigate(setupExitPath())} className="inline-flex items-center gap-2 text-sm font-black text-slate-600"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="mt-1 text-4xl font-black">Business Hours</h1><p className="mt-2 text-slate-600">Set your regular weekly operating hours. You can change these later.</p></div><div className="rounded-2xl bg-emerald-950 px-5 py-3 text-white"><p className="text-xs font-bold text-emerald-200">Asia/Kolkata</p><p className="font-black">{totalSlots} active {totalSlots===1?'period':'periods'}</p></div></header>
  {error&&<Alert tone="error">{error}</Alert>}{fields.days&&<Alert tone="error">{fields.days}</Alert>}{saved&&<Alert><span className="inline-flex items-center gap-2"><Check size={16}/>Business Hours saved.</span></Alert>}
  <section className="mt-6 rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap gap-2"><Quick onClick={()=>applyCopy(0,dayNames)}><Copy size={15}/>Copy Monday to all days</Quick><Quick onClick={()=>applyCopy(0,dayNames.slice(0,5))}>Weekdays same hours</Quick><Quick onClick={()=>applyCopy(5,dayNames.slice(5))}>Weekend same hours</Quick></div><p className="mt-3 text-xs font-bold text-slate-500">Suggested 09:00–21:00 hours are not saved until you choose Save.</p>
  <div className="mt-5 grid gap-4">{days.map((day,index)=><DayCard key={day.day} day={day} index={index} fields={fields} setMode={setMode} change={change} copyAll={()=>applyCopy(index,dayNames)}/>)}</div></section>
  <div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={saving} onClick={()=>save('dashboard')} className="rounded-xl border border-emerald-900 px-5 py-3 font-black text-emerald-900 disabled:opacity-50">Save & Return to Dashboard</button><button disabled={saving} onClick={()=>save('continue')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-900 px-5 py-3 font-black text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}Save & Continue</button></div>{dirty&&<p className="mt-3 text-center text-xs font-bold text-amber-800">You have unsaved changes.</p>}</main></div>
}

function DayCard({day,index,fields,setMode,change,copyAll}){const fieldError=Object.entries(fields).find(([key])=>key===`days.${index}`||key.startsWith(`days.${index}.`))?.[1];return <article className={`rounded-2xl border p-4 ${fieldError?'border-rose-300 bg-rose-50/30':'border-slate-200'}`}><div className="flex flex-col gap-3 xl:flex-row xl:items-start"><div className="flex min-w-40 items-center justify-between"><h2 className="text-lg font-black capitalize">{day.day}</h2><button onClick={copyAll} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title="Copy to all days"><Copy size={16}/></button></div><div className="flex flex-wrap gap-2"><Mode active={!day.closed&&!day.open24Hours} onClick={()=>setMode(index,'open')}><Sun size={15}/>Open</Mode><Mode active={day.closed} onClick={()=>setMode(index,'closed')}>Closed</Mode><Mode active={day.open24Hours} onClick={()=>setMode(index,'allDay')}><Clock3 size={15}/>Open 24 Hours</Mode></div><div className="min-w-0 flex-1">{day.closed?<StateText>Closed all day</StateText>:day.open24Hours?<StateText>Open continuously for 24 hours</StateText>:<div className="grid gap-3">{day.slots.map((slot,slotIndex)=><div key={slotIndex} className="grid items-end gap-2 sm:grid-cols-[1fr_auto_1fr_auto_auto]"><Time label="Opens" value={slot.opensAt} onChange={value=>change(index,item=>{item.slots[slotIndex].opensAt=value})}/><span className="hidden pb-3 text-slate-400 sm:block">to</span><Time label="Closes" value={slot.closesAt} onChange={value=>change(index,item=>{item.slots[slotIndex].closesAt=value})}/><label className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-black"><input type="checkbox" checked={slot.overnight} onChange={event=>change(index,item=>{item.slots[slotIndex].overnight=event.target.checked})}/><Moon size={14}/>Overnight</label><button disabled={day.slots.length===1} onClick={()=>change(index,item=>{item.slots.splice(slotIndex,1)})} className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 text-rose-700 disabled:opacity-30" title="Remove slot"><Minus size={16}/></button></div>)}<button onClick={()=>change(index,item=>{item.slots.push({opensAt:'09:00',closesAt:'17:00',overnight:false})})} className="inline-flex w-fit items-center gap-2 text-sm font-black text-emerald-800"><Plus size={16}/>Add Time Slot</button></div>}</div></div>{fieldError&&<p className="mt-3 text-sm font-bold text-rose-700">{fieldError}</p>}</article>}
function Time({label,value,onChange}){return <label><span className="text-xs font-black text-slate-600">{label}</span><input type="time" value={value} onChange={event=>onChange(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-300 px-3 font-bold outline-none focus:border-emerald-800"/></label>}
function Mode({active,onClick,children}){return <button onClick={onClick} className={`inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-black ${active?'border-emerald-900 bg-emerald-900 text-white':'border-slate-200 bg-white text-slate-600'}`}>{children}</button>}
function Quick({onClick,children}){return <button onClick={onClick} className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-900">{children}</button>}
function StateText({children}){return <div className="rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold text-slate-500">{children}</div>}
function Alert({children,tone='info'}){const style=tone==='error'?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-900';return <div className={`mt-5 rounded-xl border p-3 text-sm font-bold ${style}`}>{children}</div>}
function Center({children}){return <div className="grid min-h-screen place-content-center gap-3 bg-slate-50 text-center">{children}</div>}
