import { ArrowLeft, Bike, Car, Check, FileText, Image, Loader2, RefreshCw, Save, ShieldCheck, Truck, Upload } from 'lucide-react'
import { useEffect,useRef,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { returningToReview, setupExitPath } from '../utils/setupNavigation'

const MAX_BYTES=5*1024*1024
export default function DeliverySetupPage(){
 const navigate=useNavigate(),[state,setState]=useState(null),[type,setType]=useState(''),[registration,setRegistration]=useState(''),[ownership,setOwnership]=useState(''),[confirmed,setConfirmed]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(''),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[saved,setSaved]=useState(false),[previews,setPreviews]=useState({}),previewRef=useRef({})
 const hydrate=value=>{setState(value);setType(value.delivery.vehicle.type?.code||'');setRegistration(value.delivery.vehicle.registrationNumber||'');setOwnership(value.delivery.vehicle.ownership||'');setConfirmed(value.delivery.confirmed)}
 useEffect(()=>{(async()=>{try{hydrate(await partnerSetupService.getDelivery())}catch(e){if(e?.response?.data?.error?.code==='PARTNER_SETUP_NOT_APPLICABLE'){navigate(setupExitPath(),{replace:true});return}setError(e?.response?.data?.error?.userMessage||'Delivery Partner Setup could not be loaded.')}finally{setLoading(false)}})()},[navigate])
 useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty]);useEffect(()=>{previewRef.current=previews},[previews]);useEffect(()=>()=>Object.values(previewRef.current).forEach(URL.revokeObjectURL),[])
 useEffect(()=>{if(!state)return;let cancelled=false;(async()=>{const next={};for(const item of state.delivery.documents){if(!item.document)continue;try{const blob=await partnerSetupService.getDocumentBlob(item.document.reference);if(cancelled)return;next[item.code]=URL.createObjectURL(blob)}catch{/* Status remains usable if preview is unavailable. */}}if(!cancelled)setPreviews(old=>{Object.values(old).forEach(URL.revokeObjectURL);return next})})();return()=>{cancelled=true}},[state])
 const chooseType=code=>{const option=state.options.vehicleTypes.find(x=>x.code===code);setType(code);if(!option?.requirements.registrationRequired)setRegistration('');setDirty(true);setSaved(false);setFields({})}
 const save=async destination=>{setSaving(true);setError('');setFields({});try{const value=await partnerSetupService.saveDelivery({vehicleType:type,vehicleRegistrationNumber:registration,vehicleOwnership:ownership,confirmed});hydrate(value);setDirty(false);setSaved(true);if(returningToReview()||destination==='return')navigate(setupExitPath())}catch(e){setFields(e?.response?.data?.error?.fieldErrors||{});setError(e?.response?.data?.error?.userMessage||'Delivery Partner Setup could not be saved.')}finally{setSaving(false)}}
 const upload=async(code,file)=>{if(!file)return;if(file.size>MAX_BYTES){setError('File is too large. Maximum file size is 5 MB.');return}if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)){setError('This file type is not supported.');return}setUploading(code);setError('');try{await partnerSetupService.uploadDocument(code,file);hydrate(await partnerSetupService.getDelivery());setSaved(true)}catch(e){setError(e?.response?.data?.error?.userMessage||'The document could not be uploaded.')}finally{setUploading('')}}
 if(loading)return <Center><Loader2 className="animate-spin"/>Loading Delivery Partner Setup…</Center>
 return <div className="min-h-screen bg-[#f4f7f4] px-4 py-7"><main className="mx-auto max-w-5xl"><button onClick={()=>dirty?confirm('Discard unsaved Delivery Setup changes?')&&navigate(setupExitPath()):navigate(setupExitPath())} className="inline-flex items-center gap-2 font-black text-slate-600"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-6"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="mt-1 text-4xl font-black">Delivery Partner Setup</h1><p className="mt-2 text-slate-600">Add your delivery vehicle details and complete the required verification information.</p></header>{error&&<Alert bad>{error}</Alert>}{saved&&<Alert><Check size={17}/>Your Delivery Setup has been saved.</Alert>}
 <section className="mt-6 rounded-[2rem] bg-emerald-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Delivery Partner</p><h2 className="mt-2 text-2xl font-black">{state?.delivery.partnerName}</h2><p className="text-emerald-200">Independent Delivery identity · setup does not make you online</p></section>
 <section className="mt-5 rounded-[2rem] border bg-white p-5 sm:p-6"><h2 className="text-xl font-black">What vehicle do you use?</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{state?.options.vehicleTypes.map(option=><button type="button" key={option.code} onClick={()=>chooseType(option.code)} className={`min-h-28 rounded-2xl border p-4 text-left ${type===option.code?'border-emerald-800 bg-emerald-50':'border-slate-200'}`}><VehicleIcon code={option.code}/><b className="mt-2 block">{option.name}</b>{type===option.code&&<Check className="float-right -mt-5 text-emerald-800" size={17}/>}</button>)}</div>{fields.vehicleType&&<Err>{fields.vehicleType}</Err>}
 {state?.requirements.registrationRequired&&<label className="mt-5 block font-black">Vehicle Registration Number<input value={registration} onChange={e=>{setRegistration(e.target.value.toUpperCase());setDirty(true)}} placeholder="UP32AB1234" className="mt-2 w-full rounded-xl border p-3 uppercase"/><small className="mt-1 block font-medium text-slate-500">Spaces and hyphens are removed when saved. This is format validation, not government verification.</small>{fields.vehicleRegistrationNumber&&<Err>{fields.vehicleRegistrationNumber}</Err>}</label>}
 <div className="mt-5"><h3 className="font-black">Vehicle ownership</h3><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{state?.options.ownershipTypes.map(x=><button type="button" key={x.code} onClick={()=>{setOwnership(x.code);setDirty(true)}} className={`min-h-12 rounded-xl border px-3 font-black ${ownership===x.code?'border-emerald-800 bg-emerald-50':'border-slate-200'}`}>{x.name}</button>)}</div>{fields.vehicleOwnership&&<Err>{fields.vehicleOwnership}</Err>}</div></section>
 {type&&<section className="mt-5 rounded-[2rem] border bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck className="text-emerald-800"/><div><h2 className="text-xl font-black">Required verification</h2><p className="text-sm text-slate-500">Requirements are calculated by the server for your selected vehicle.</p></div></div>{state.delivery.documents.length?<div className="mt-5 grid gap-4 md:grid-cols-2">{state.delivery.documents.map(item=><DocumentCard key={item.code} item={item} preview={previews[item.code]} uploading={uploading===item.code} onUpload={file=>upload(item.code,file)}/>)}</div>:<p className="mt-5 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-900">No vehicle documents are required for this vehicle type.</p>}</section>}
 <section className="mt-5 rounded-[2rem] border bg-white p-5 sm:p-6"><label className="flex gap-3 rounded-xl bg-slate-50 p-4 font-bold"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setDirty(true)}} className="h-6 w-6 shrink-0 accent-emerald-800"/>I confirm that the vehicle and delivery information provided above is correct.</label>{fields.confirmed&&<Err>{fields.confirmed}</Err>}<div className="mt-4 rounded-xl bg-sky-50 p-4 text-sm text-sky-950"><b>Completing setup does not activate delivery jobs immediately.</b><p>Your profile will be reviewed before activation. You will remain offline and unapproved.</p></div></section>
 {state?.remainingRequirements.length>0&&<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><b>Still required before completion:</b><p className="mt-1 text-sm">{state.remainingRequirements.map(labelRequirement).join(' · ')}</p></div>}
 <div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={saving||Boolean(uploading)} onClick={()=>save('return')} className="min-h-13 rounded-xl border border-emerald-900 p-3 font-black">Save &amp; Return</button><button disabled={saving||Boolean(uploading)} onClick={()=>save('complete')} className="flex min-h-13 items-center justify-center gap-2 rounded-xl bg-emerald-900 p-3 font-black text-white">{saving?<Loader2 className="animate-spin"/>:<Save size={18}/>}Complete Delivery Setup</button></div>{state?.setup.completionPercentage===100&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-center font-bold text-emerald-900">Delivery Partner setup information is complete. Return to Setup Center to review it.</p>}</main></div>
}
function DocumentCard({item,preview,uploading,onUpload}){const input=useRef(null),status=item.reviewStatus;return <article className={`rounded-2xl border p-4 ${status==='needs_correction'||status==='rejected'?'border-amber-300 bg-amber-50':'border-slate-200'}`}><div className="flex justify-between gap-2"><div><b>{item.label}</b><small className="block text-slate-500">{item.required?'Required':'Optional'}</small></div><Status item={item}/></div><div className="mt-3 grid min-h-32 place-items-center overflow-hidden rounded-xl bg-slate-100">{preview&&item.document?.fileType==='image'?<img src={preview} alt={`${item.label} preview`} className="h-32 w-full object-contain"/>:item.document?.fileType==='pdf'?<button onClick={()=>preview&&window.open(preview,'_blank','noopener,noreferrer')} className="grid gap-1 text-center font-black"><FileText className="mx-auto"/>View PDF</button>:<Image className="text-slate-400"/>}</div><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" onChange={e=>{onUpload(e.target.files?.[0]);e.target.value=''}}/><button disabled={uploading} onClick={()=>input.current?.click()} className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-900 font-black text-white">{uploading?<Loader2 className="animate-spin"/>:item.uploaded?<RefreshCw/>:<Upload/>}{uploading?'Uploading…':item.uploaded?'Replace':'Upload'}</button></article>}
function Status({item}){if(!item.uploaded)return <Pill>Not uploaded</Pill>;if(item.reviewStatus==='approved')return <Pill green>Approved</Pill>;if(item.reviewStatus==='needs_correction'||item.reviewStatus==='rejected')return <Pill warn>Needs correction</Pill>;return <Pill blue>Pending</Pill>}
function Pill({children,green,warn,blue}){return <span className={`h-fit rounded-full px-2 py-1 text-xs font-black ${green?'bg-emerald-100 text-emerald-800':warn?'bg-amber-100 text-amber-900':blue?'bg-sky-100 text-sky-800':'bg-slate-100 text-slate-600'}`}>{children}</span>}
function VehicleIcon({code}){if(code==='car')return <Car/>;if(code==='mini_truck')return <Truck/>;return <Bike/>}
function labelRequirement(x){return({vehicleType:'Vehicle type',vehicleRegistrationNumber:'Registration number',vehicleOwnership:'Vehicle ownership',DRIVING_LICENCE_FRONT:'Driving Licence',VEHICLE_RC_FRONT:'Vehicle RC',VEHICLE_INSURANCE:'Vehicle Insurance',confirmation:'Confirmation'})[x]||x}
function Alert({children,bad}){return <div className={`mt-5 flex gap-2 rounded-xl border p-3 font-bold ${bad?'bg-rose-50 text-rose-800':'bg-emerald-50 text-emerald-900'}`}>{children}</div>}
function Err({children}){return <p className="mt-2 text-sm font-bold text-rose-700">{children}</p>}
function Center({children}){return <div className="grid min-h-screen place-content-center gap-3 text-center">{children}</div>}

