import { ArrowLeft, Check, ChevronRight, FileText, Image, Loader2, RefreshCw, ShieldCheck, Upload } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { setupExitPath } from '../utils/setupNavigation'

const MAX_BYTES=5*1024*1024
export default function DocumentsPage(){
  const navigate=useNavigate(),[state,setState]=useState(null),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[previews,setPreviews]=useState({}),[previewErrors,setPreviewErrors]=useState({}),previewRef=useRef({})
  useEffect(()=>{(async()=>{try{setState(await partnerSetupService.getDocuments())}catch(e){setError(e?.response?.data?.error?.userMessage||'Documents could not be loaded.')}finally{setLoading(false)}})()},[])
  useEffect(()=>{previewRef.current=previews},[previews])
  useEffect(()=>()=>Object.values(previewRef.current).forEach(URL.revokeObjectURL),[])
  useEffect(()=>{if(!state)return;let cancelled=false;(async()=>{const next={},failures={};for(const requirement of state.requirements){if(!requirement.document)continue;try{const blob=await partnerSetupService.getDocumentBlob(requirement.document.reference);if(cancelled)return;next[requirement.code]=URL.createObjectURL(blob)}catch{failures[requirement.code]='Saved document preview could not be loaded. You can replace the document.'}}if(!cancelled){setPreviewErrors(failures);setPreviews(current=>{Object.values(current).forEach(URL.revokeObjectURL);return next})}})();return()=>{cancelled=true}},[state])
  const upload=async(code,file)=>{if(!file)return;if(file.size>MAX_BYTES){setError('File is too large. Maximum file size is 5 MB.');return}const allowed=['image/jpeg','image/png','image/webp','application/pdf'];if(!allowed.includes(file.type)){setError('This file type is not supported.');return}setUploading(code);setError('');setSuccess('');try{setState(await partnerSetupService.uploadDocument(code,file));setSuccess(`${label(code)} uploaded. It is pending verification.`)}catch(e){setError(e?.response?.data?.error?.userMessage||"We couldn't upload this document. Please try again.")}finally{setUploading('')}}
  const continueSetup=()=>{const next=state.setup?.steps?.find(step=>step.code===state.setup?.nextRecommendedStep);navigate(next?`/setup/${next.routeCode}`:'/setup')}
  if(loading)return <Center><Loader2 className="animate-spin text-emerald-800"/><p>Loading Documents…</p></Center>
  return <div className="min-h-screen bg-[#f4f7f4] px-4 py-8 text-slate-950"><main className="mx-auto max-w-5xl"><button disabled={Boolean(uploading)} onClick={()=>navigate(setupExitPath())} className="inline-flex items-center gap-2 text-sm font-black text-slate-600 disabled:opacity-50"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-7 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="mt-1 text-4xl font-black">Documents & Verification</h1><p className="mt-2 text-slate-600">Upload the required documents for verification.</p></div>{state&&<div className="rounded-2xl bg-emerald-950 px-5 py-3 text-white"><p className="text-2xl font-black">{state.uploadedCount} of {state.requiredCount}</p><p className="text-xs font-bold text-emerald-200">requirements complete</p></div>}</header>{error&&<Alert tone="error">{error}</Alert>}{success&&<Alert>{success}</Alert>}
  <div className="mt-7 grid gap-5 md:grid-cols-2">{state?.requirements.map(requirement=><DocumentCard key={requirement.code} requirement={requirement} uploading={uploading===requirement.code} preview={previews[requirement.code]} previewError={previewErrors[requirement.code]} onUpload={file=>upload(requirement.code,file)}/>)}</div>
  <section className="mt-6 rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-950"><div className="flex gap-3"><ShieldCheck className="shrink-0" size={20}/><div><p className="font-black">Your documents are stored privately.</p><p className="mt-1">Uploading does not mean they are approved. Essivery’s verification team will review them separately.</p></div></div></section>
  <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-between"><button disabled={Boolean(uploading)} onClick={()=>navigate('/dashboard')} className="rounded-xl border border-emerald-900 px-5 py-3 font-black text-emerald-900 disabled:opacity-50">Return to Dashboard</button><button disabled={Boolean(uploading)||state?.step?.status!=='complete'} onClick={continueSetup} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-900 px-5 py-3 font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Continue to Bank<ChevronRight size={17}/></button></div>{state?.step?.status!=='complete'&&<p className="mt-3 text-right text-xs font-bold text-slate-500">Upload all unresolved documents to continue.</p>}</main></div>
}
function DocumentCard({requirement,uploading,preview,previewError,onUpload}){const input=useRef(null),doc=requirement.document,status=requirement.reviewStatus;return <article className={`rounded-[2rem] border bg-white p-5 shadow-sm ${status==='needs_correction'||status==='rejected'?'border-amber-300':'border-slate-200'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Required document</p><h2 className="mt-1 text-xl font-black">{requirement.label}</h2></div><Status requirement={requirement}/></div><div className="mt-5 grid min-h-44 place-items-center overflow-hidden rounded-2xl bg-slate-100">{preview&&doc?.fileType==='image'?<img src={preview} alt={`${requirement.label} preview`} className="h-44 w-full object-contain"/>:preview&&doc?.fileType==='pdf'?<button onClick={()=>window.open(preview,'_blank','noopener,noreferrer')} className="grid place-items-center gap-2 p-5 font-black text-emerald-900"><FileText size={42}/>View PDF</button>:<div className="grid place-items-center gap-2 text-slate-400"><Image size={42}/><span className="text-sm font-bold">{doc?'Preview unavailable':'No document uploaded'}</span></div>}</div>{previewError&&<p className="mt-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-800">{previewError}</p>}{(status==='needs_correction'||status==='rejected')&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">This document needs to be uploaded again.</p>}<input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={event=>{onUpload(event.target.files?.[0]);event.target.value=''}}/><button disabled={uploading} onClick={()=>input.current?.click()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-900 px-4 py-3 font-black text-white disabled:opacity-50">{uploading?<Loader2 className="animate-spin" size={18}/>:doc?<RefreshCw size={18}/>:<Upload size={18}/>} {uploading?'Uploading…':doc?'Replace document':'Choose File'}</button><p className="mt-2 text-center text-xs font-bold text-slate-400">JPEG, PNG, WebP or PDF · maximum 5 MB</p></article>}
function Status({requirement}){const status=requirement.reviewStatus;if(!requirement.uploaded)return <Pill>Not uploaded</Pill>;if(status==='approved')return <Pill tone="green"><Check size={13}/>Approved</Pill>;if(status==='needs_correction')return <Pill tone="amber">Needs correction</Pill>;if(status==='rejected')return <Pill tone="red">Rejected</Pill>;return <Pill tone="blue">Pending verification</Pill>}
function Pill({children,tone='gray'}){const styles={gray:'bg-slate-100 text-slate-600',green:'bg-emerald-100 text-emerald-800',amber:'bg-amber-100 text-amber-900',red:'bg-rose-100 text-rose-800',blue:'bg-sky-100 text-sky-800'};return <span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-black ${styles[tone]}`}>{children}</span>}
function Alert({children,tone='info'}){return <div className={`mt-5 rounded-xl border p-3 text-sm font-bold ${tone==='error'?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-900'}`}>{children}</div>}
function Center({children}){return <div className="grid min-h-screen place-content-center gap-3 bg-slate-50 text-center">{children}</div>}
function label(code){return code==='PAN'?'PAN Card':code==='AADHAAR_FRONT'?'Aadhaar Front':'Aadhaar Back'}
