import { ArrowLeft, Check, Headphones, Home, Loader2, Save, Search, Settings2 } from 'lucide-react'
import { useEffect,useMemo,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { returningToReview, setupExitPath } from '../utils/setupNavigation'

export default function HomeServiceSetupPage(){
  const navigate=useNavigate(),[state,setState]=useState(null),[codes,setCodes]=useState([]),[preference,setPreference]=useState(''),[confirmed,setConfirmed]=useState(false),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[saved,setSaved]=useState(false)
  useEffect(()=>{(async()=>{try{const value=await partnerSetupService.getHomeService();setState(value);setCodes(value.homeService.services.map(x=>x.code));setPreference(value.homeService.setupPreference||'');setConfirmed(value.homeService.confirmed)}catch(e){if(e?.response?.data?.error?.code==='PARTNER_SETUP_NOT_APPLICABLE'){navigate(setupExitPath(),{replace:true});return}setError(e?.response?.data?.error?.userMessage||'Home Service Setup could not be loaded.')}finally{setLoading(false)}})()},[navigate])
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty])
  const groups=useMemo(()=>(state?.options.groups||[]).map(group=>({...group,services:group.services.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()))})).filter(group=>group.services.length),[state,search])
  const toggle=code=>{setCodes(value=>value.includes(code)?value.filter(x=>x!==code):value.length<20?[...value,code]:value);setDirty(true);setSaved(false);setFields({})}
  const save=async destination=>{setSaving(true);setError('');setFields({});try{const value=await partnerSetupService.saveHomeService({services:codes,setupPreference:preference,confirmed});setState(value);setCodes(value.homeService.services.map(x=>x.code));setPreference(value.homeService.setupPreference);setConfirmed(value.homeService.confirmed);setDirty(false);setSaved(true);if(returningToReview()||destination==='return')navigate(setupExitPath())}catch(e){setFields(e?.response?.data?.error?.fieldErrors||{});setError(e?.response?.data?.error?.userMessage||'Home Service Setup could not be saved.')}finally{setSaving(false)}}
  if(loading)return <Center><Loader2 className="animate-spin"/>Loading Home Service Setup…</Center>
  return <div className="min-h-screen bg-[#f4f7f4] px-4 py-8"><main className="mx-auto max-w-4xl"><button onClick={()=>dirty?confirm('Discard unsaved Home Service Setup changes?')&&navigate(setupExitPath()):navigate(setupExitPath())} className="inline-flex items-center gap-2 font-black text-slate-600"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-7"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="text-4xl font-black">Home Service Setup</h1><p className="mt-2 text-slate-600">Choose the services you intend to offer. Pricing, staff, availability, and activation come later.</p></header>{error&&<Alert bad>{error}</Alert>}{saved&&<Alert><Check size={17}/>Home Service Setup is complete. Your profile is not approved, bookable, or live yet.</Alert>}
  <section className="mt-6 rounded-[2rem] bg-emerald-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Provider summary</p><div className="mt-3 flex items-center gap-4"><span className="rounded-2xl bg-white/10 p-4"><Home/></span><div><h2 className="text-2xl font-black">{state?.homeService.businessName}</h2><p className="text-emerald-200">{state?.homeService.category.name} · selected during registration</p></div></div></section>
  <section className="mt-5 rounded-[2rem] border bg-white p-6"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-black">Select services you offer</h2><p className="text-sm text-slate-500">Choose 1–20 active services from Essivery’s service master.</p></div><b>{codes.length}/20</b></div><div className="relative mt-4"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search services" className="w-full rounded-xl border p-3 pl-10"/></div><div className="mt-4 max-h-96 space-y-5 overflow-auto">{groups.map(group=><div key={`${group.category.code}/${group.subcategory?.code||'other'}`}><h3 className="font-black">{group.category.name}{group.subcategory&&<span className="font-medium text-slate-500"> · {group.subcategory.name}</span>}</h3><div className="mt-2 flex flex-wrap gap-2">{group.services.map(service=><button type="button" key={service.code} onClick={()=>toggle(service.code)} className={`rounded-full border px-4 py-2 text-sm font-black ${codes.includes(service.code)?'border-emerald-800 bg-emerald-100 text-emerald-900':'border-slate-200'}`}>{codes.includes(service.code)&&<Check className="mr-1 inline" size={14}/>} {service.name}</button>)}</div></div>)}</div>{!groups.length&&<p className="mt-4 rounded-xl bg-slate-50 p-4 text-slate-600">No active services match your search.</p>}{fields.services&&<Err>{fields.services}</Err>}</section>
  <section className="mt-5 rounded-[2rem] border bg-white p-6"><h2 className="text-xl font-black">How would you like to prepare your service listings?</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Option icon={Settings2} active={preference==='SELF'} title="I'll set them up myself" text="You can add service details in a later phase." onClick={()=>{setPreference('SELF');setDirty(true)}}/><Option icon={Headphones} active={preference==='ASSISTED'} title="I need Essivery assistance" text="Our team can help prepare your service listings later." onClick={()=>{setPreference('ASSISTED');setDirty(true)}}/></div>{fields.setupPreference&&<Err>{fields.setupPreference}</Err>}<label className="mt-5 flex gap-3 rounded-xl bg-slate-50 p-4 font-bold"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setDirty(true)}} className="h-5 w-5 accent-emerald-800"/>I confirm that these are the services I intend to offer.</label>{fields.confirmed&&<Err>{fields.confirmed}</Err>}<div className="mt-5 rounded-xl bg-sky-50 p-4 text-sm text-sky-950"><b>This step does not publish your business or create bookable services.</b><p>Pricing, staff, slots, availability, approval, and marketplace activation remain unchanged.</p></div></section>
  <div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={saving} onClick={()=>save('return')} className="rounded-xl border border-emerald-900 p-3 font-black">Save &amp; Return</button><button disabled={saving} onClick={()=>save('complete')} className="flex items-center justify-center gap-2 rounded-xl bg-emerald-900 p-3 font-black text-white">{saving?<Loader2 className="animate-spin"/>:<Save size={18}/>}Complete Home Service Setup</button></div>{state?.setup?.completionPercentage===100&&<p className="mt-4 rounded-xl bg-emerald-50 p-4 text-center font-bold text-emerald-900">Business setup information is complete. Return to Setup Center to review it.</p>}</main></div>
}
function Option({icon:Icon,active,title,text,onClick}){return <button type="button" onClick={onClick} className={`flex gap-3 rounded-2xl border p-4 text-left ${active?'border-emerald-800 bg-emerald-50':'border-slate-200'}`}><Icon/><span><b>{title}</b><small className="mt-1 block text-slate-500">{text}</small></span></button>}
function Alert({children,bad}){return <div className={`mt-5 flex gap-2 rounded-xl border p-3 font-bold ${bad?'bg-rose-50 text-rose-800':'bg-emerald-50 text-emerald-900'}`}>{children}</div>}
function Err({children}){return <p className="mt-2 text-sm font-bold text-rose-700">{children}</p>}
function Center({children}){return <div className="grid min-h-screen place-content-center gap-3 text-center">{children}</div>}

