import { ArrowLeft, Bike, Check, ChevronRight, Loader2, MapPin, PackageCheck, Save, Store } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { returningToReview, setupExitPath } from '../utils/setupNavigation'

const retailDefaults={essiveryDelivery:false,selfDelivery:false,customerPickup:false}

export default function OperationsPage(){
  const navigate=useNavigate(),[type,setType]=useState('retail'),[form,setForm]=useState(retailDefaults),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[saved,setSaved]=useState(false)
  useEffect(()=>{(async()=>{try{const data=await partnerSetupService.getOperations();setType(data.type);setForm(data.fulfilment);setDirty(false)}catch(e){if(e?.response?.data?.error?.code==='PARTNER_SETUP_NOT_APPLICABLE'){navigate(setupExitPath(),{replace:true});return}setError(e?.response?.data?.error?.userMessage||'Operations could not be loaded.')}finally{setLoading(false)}})()},[navigate])
  useEffect(()=>{const warn=event=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
  const enabled=useMemo(()=>Object.values(form).filter(Boolean).length,[form])
  const toggle=key=>{setForm(current=>({...current,[key]:!current[key]}));setDirty(true);setSaved(false);setFields({});setError('')}
  const save=async(destination)=>{setSaving(true);setFields({});setError('');try{const result=await partnerSetupService.saveOperations(form);setForm(result.fulfilment);setDirty(false);setSaved(true);if(returningToReview()){navigate('/setup/review');return}if(destination==='dashboard')navigate('/dashboard');if(destination==='continue'){const next=result.setup?.steps?.find(step=>step.code===result.setup?.nextRecommendedStep);navigate(next?`/setup/${next.routeCode}`:'/setup')}}catch(e){setFields(e?.response?.data?.error?.fieldErrors||{});setError(e?.response?.data?.error?.userMessage||'Operations could not be saved.')}finally{setSaving(false)}}
  if(loading)return <Center><Loader2 className="animate-spin text-emerald-800"/><p>Loading Operations…</p></Center>
  const home=type==='home_service',restaurant=type==='restaurant'
  return <div className="min-h-screen bg-[#f4f7f4] px-4 py-8 text-slate-950"><main className="mx-auto max-w-4xl"><button onClick={()=>navigate(setupExitPath())} className="inline-flex items-center gap-2 text-sm font-black text-slate-600"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-7"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="mt-1 text-4xl font-black">{home?'Service Operations':'Operations & Fulfilment'}</h1><p className="mt-2 text-slate-600">{home?'Choose how you provide services to customers.':'Choose how you want to fulfil orders on Essivery.'}</p></header>
  {error&&<Alert tone="error">{error}</Alert>}{fields.fulfilment&&<Alert tone="error">{fields.fulfilment}</Alert>}{saved&&<Alert><span className="inline-flex items-center gap-2"><Check size={16}/>Operations preferences saved.</span></Alert>}
  <section className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">{home?'Where do you provide services?':'How will you fulfil orders?'}</h2><p className="mt-1 text-sm text-slate-500">Select at least one option. You can update it later.</p></div><span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-black text-emerald-800">{enabled} selected</span></div><div className="mt-6 grid gap-3">{home?<Option icon={MapPin} title="Service at Customer Location" description="Provide services at the customer's address." checked={form.serviceAtCustomerLocation} error={fields.serviceAtCustomerLocation} onClick={()=>toggle('serviceAtCustomerLocation')}/>:<><Option icon={Bike} title="Essivery Delivery" description="Essivery delivery partners can handle eligible deliveries." checked={form.essiveryDelivery} onClick={()=>toggle('essiveryDelivery')}/><Option icon={PackageCheck} title="Self Delivery" description="Deliver orders using your own staff or resources." checked={form.selfDelivery} onClick={()=>toggle('selfDelivery')}/><Option icon={Store} title={restaurant?'Takeaway / Customer Pickup':'Customer Pickup'} description="Customers can collect orders from your business location." checked={form.customerPickup} onClick={()=>toggle('customerPickup')}/></>}</div><div className="mt-6 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><p className="font-black text-slate-800">This step saves preferences only.</p><p className="mt-1">It does not make your business live, approve it, configure service areas, or guarantee delivery availability.</p></div></section>
  <div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={saving} onClick={()=>save('dashboard')} className="rounded-xl border border-emerald-900 px-5 py-3 font-black text-emerald-900 disabled:opacity-50">Save & Return</button><button disabled={saving} onClick={()=>save('continue')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-900 px-5 py-3 font-black text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}Save & Continue<ChevronRight size={17}/></button></div>{dirty&&<p className="mt-3 text-center text-xs font-bold text-amber-800">You have unsaved changes.</p>}</main></div>
}
function Option({icon:Icon,title,description,checked,error,onClick}){return <button type="button" role="checkbox" aria-checked={checked} onClick={onClick} className={`flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition ${checked?'border-emerald-800 bg-emerald-50':'border-slate-200 hover:border-emerald-300'} ${error?'border-rose-400':''}`}><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${checked?'bg-emerald-900 text-white':'bg-slate-100 text-slate-500'}`}><Icon size={21}/></span><span className="min-w-0 flex-1"><strong className="block font-black">{title}</strong><span className="mt-1 block text-sm text-slate-500">{description}</span>{error&&<span className="mt-1 block text-xs font-bold text-rose-700">{error}</span>}</span><span className={`grid h-6 w-6 place-items-center rounded-full border ${checked?'border-emerald-900 bg-emerald-900 text-white':'border-slate-300'}`}>{checked&&<Check size={15}/>}</span></button>}
function Alert({children,tone='info'}){const style=tone==='error'?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-900';return <div className={`mt-5 rounded-xl border p-3 text-sm font-bold ${style}`}>{children}</div>}
function Center({children}){return <div className="grid min-h-screen place-content-center gap-3 bg-slate-50 text-center">{children}</div>}
