import { ArrowLeft, Check, ChevronRight, Headphones, Loader2, PackagePlus, Save, Store } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { partnerSetupService } from '../services/partner/partnerSetupService'
import { returningToReview, setupExitPath } from '../utils/setupNavigation'

export default function RetailSetupPage(){
  const navigate=useNavigate(),[state,setState]=useState(null),[mode,setMode]=useState(''),[confirmed,setConfirmed]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[saved,setSaved]=useState(false)
  useEffect(()=>{(async()=>{try{const result=await partnerSetupService.getRetail();setState(result);setMode(result.retail.catalogueSetupMode||'');setConfirmed(result.retail.confirmed);setDirty(false)}catch(e){if(e?.response?.data?.error?.code==='PARTNER_SETUP_NOT_APPLICABLE'){navigate(setupExitPath(),{replace:true});return}setError(e?.response?.data?.error?.userMessage||'Retail Setup could not be loaded.')}finally{setLoading(false)}})()},[navigate])
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty])
  const choose=value=>{setMode(value);setDirty(true);setSaved(false);setFields({});setError('')}
  const save=async destination=>{setSaving(true);setFields({});setError('');try{const result=await partnerSetupService.saveRetail({catalogueSetupMode:mode,confirmed});setState(result);setMode(result.retail.catalogueSetupMode);setConfirmed(result.retail.confirmed);setDirty(false);setSaved(true);if(returningToReview()||destination==='return')navigate(setupExitPath())}catch(e){setFields(e?.response?.data?.error?.fieldErrors||{});setError(e?.response?.data?.error?.userMessage||'Retail Setup could not be saved.')}finally{setSaving(false)}}
  if(loading)return <Center><Loader2 className="animate-spin text-emerald-800"/><p>Loading Retail Setup…</p></Center>
  const category=state?.retail?.category
  return <div className="min-h-screen bg-[#f4f7f4] px-4 py-8 text-slate-950"><main className="mx-auto max-w-4xl"><button onClick={()=>dirty?confirm('Discard unsaved Retail Setup changes?')&&navigate(setupExitPath()):navigate(setupExitPath())} className="inline-flex items-center gap-2 text-sm font-black text-slate-600"><ArrowLeft size={17}/>Back to Setup Center</button><header className="mt-7"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Business Setup</p><h1 className="mt-1 text-4xl font-black">Retail Store Setup</h1><p className="mt-2 text-slate-600">Confirm your store category and choose how you want to prepare your Essivery catalogue.</p></header>
  {error&&<Alert tone="error">{error}</Alert>}{saved&&<Alert><span className="inline-flex items-center gap-2"><Check size={16}/>Retail Setup is complete. Your store is not live until review and approval.</span></Alert>}
  <section className="mt-7 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">My Store Category</p><div className="mt-4 flex items-center gap-4"><span className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-emerald-100 text-emerald-900">{category?.iconUrl?<img src={category.iconUrl} alt="" className="h-full w-full object-cover"/>:<Store size={28}/>}</span><div><h2 className="text-2xl font-black">{category?.name}</h2><p className="font-bold text-slate-600">{state?.retail?.businessName}</p><p className="mt-1 text-xs font-bold text-slate-400">Selected during registration · Read-only</p></div></div><a href="mailto:support@essivery.in" className="mt-5 inline-block text-sm font-black text-emerald-800 underline">Wrong category? Contact Support</a></section>
  <section className="mt-5 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">How would you like to set up your product catalogue?</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Option icon={PackagePlus} selected={mode==='SELF'} title="I'll add products myself" description="You'll be able to choose and manage products after setup." onClick={()=>choose('SELF')}/><Option icon={Headphones} selected={mode==='ASSISTED'} title="I need Essivery assistance" description="Our team can help you prepare your catalogue." onClick={()=>choose('ASSISTED')}/></div>{fields.catalogueSetupMode&&<p className="mt-2 text-sm font-bold text-rose-700">{fields.catalogueSetupMode}</p>}
  <label className={`mt-6 flex cursor-pointer items-start gap-3 rounded-2xl border p-4 ${fields.confirmed?'border-rose-400 bg-rose-50':'border-slate-200 bg-slate-50'}`}><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setDirty(true);setSaved(false);setFields(current=>({...current,confirmed:undefined}))}} className="mt-1 h-5 w-5 accent-emerald-800"/><span className="font-bold">I confirm that this store belongs to the selected category and the information provided is correct.{fields.confirmed&&<small className="mt-1 block text-rose-700">{fields.confirmed}</small>}</span></label>
  <div className="mt-5 rounded-2xl bg-sky-50 p-4 text-sm text-sky-950"><p className="font-black">Product catalogue setup comes next after your Partner profile is submitted.</p><p className="mt-1">This step does not add products, publish your catalogue, approve your profile, or make your store live.</p></div></section>
  <div className="mt-6 grid gap-3 sm:grid-cols-2"><button disabled={saving} onClick={()=>save('return')} className="rounded-xl border border-emerald-900 px-5 py-3 font-black text-emerald-900 disabled:opacity-50">Save &amp; Return</button><button disabled={saving} onClick={()=>save('complete')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-900 px-5 py-3 font-black text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={17}/>:<Save size={17}/>}Complete Retail Setup<ChevronRight size={17}/></button></div>{state?.setup?.completionPercentage===100&&<div className="mt-4 rounded-xl bg-emerald-50 p-4 text-center font-bold text-emerald-900">Business setup information is complete. Return to the Setup Center or Dashboard; Review &amp; Submit will be available in a later phase.</div>}{dirty&&<p className="mt-3 text-center text-xs font-bold text-amber-800">You have unsaved changes.</p>}</main></div>
}
function Option({icon:Icon,selected,title,description,onClick}){return <button type="button" role="radio" aria-checked={selected} onClick={onClick} className={`flex min-h-36 items-start gap-4 rounded-2xl border p-5 text-left ${selected?'border-emerald-800 bg-emerald-50':'border-slate-200 hover:border-emerald-300'}`}><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-xl ${selected?'bg-emerald-900 text-white':'bg-slate-100 text-slate-500'}`}><Icon size={22}/></span><span><strong className="block font-black">{title}</strong><span className="mt-2 block text-sm text-slate-500">{description}</span></span></button>}
function Alert({children,tone='info'}){return <div className={`mt-5 rounded-xl border p-3 text-sm font-bold ${tone==='error'?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-900'}`}>{children}</div>}
function Center({children}){return <div className="grid min-h-screen place-content-center gap-3 bg-slate-50 text-center">{children}</div>}
