<?php
declare(strict_types=1);namespace Essivery\Partner\Repositories;
use Essivery\Api\Core\ApiException;use Essivery\Api\Core\Helpers;use Essivery\Partner\Domain\PartnerContext;use PDO;
final class PartnerReviewRepository
{
 public function __construct(private PDO$pdo){}
 public function application(PartnerContext$c,bool$lock=false):array{$column=$c->deliveryPartnerId!==null?'delivery_partner_id':'business_partner_id';$owner=$c->deliveryPartnerId??$c->businessPartnerId;$suffix=$lock&&$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)!=='sqlite'?' FOR UPDATE':'';$q=$this->pdo->prepare("SELECT * FROM partner_onboarding_applications WHERE $column=:owner AND is_current=1 AND status='active' LIMIT 1".$suffix);$q->execute(['owner'=>$owner]);return$q->fetch()?:[];}
 public function steps(int$application):array{$q=$this->pdo->prepare("SELECT step_code,requirement_type,is_required,step_status,completed_at FROM partner_onboarding_steps WHERE application_id=:application AND status='active' ORDER BY id");$q->execute(['application'=>$application]);return$q->fetchAll();}
 public function personal(PartnerContext$c):array{if($c->deliveryPartnerId!==null){$q=$this->pdo->prepare("SELECT name owner_name,mobile,email FROM delivery_partners WHERE id=:owner AND user_id=:user AND deleted_at IS NULL");$q->execute(['owner'=>$c->deliveryPartnerId,'user'=>$c->authenticatedUserId]);}else{$q=$this->pdo->prepare("SELECT owner_name,mobile,email FROM partners WHERE id=:owner AND user_id=:user AND deleted_at IS NULL");$q->execute(['owner'=>$c->businessPartnerId,'user'=>$c->authenticatedUserId]);}return$q->fetch()?:[];}
 public function business(PartnerContext$c):array{$q=$this->pdo->prepare("SELECT p.business_name,p.tax_number,c.name category_name FROM partners p LEFT JOIN parent_categories c ON c.id=:category WHERE p.id=:owner AND p.user_id=:user AND p.deleted_at IS NULL");$q->execute(['category'=>$c->parentCategoryId,'owner'=>$c->businessPartnerId,'user'=>$c->authenticatedUserId]);return$q->fetch()?:[];}
 public function location(PartnerContext$c):array{$table=$c->deliveryPartnerId!==null?'delivery_partners':'partners';$id=$c->deliveryPartnerId??$c->businessPartnerId;$line=$c->deliveryPartnerId!==null?'address_line':'address_line_1';$q=$this->pdo->prepare("SELECT o.$line address_line_1,o.address_line_2,o.locality,o.landmark,o.pincode,o.latitude,o.longitude,ci.name city,st.name state FROM $table o LEFT JOIN cities ci ON ci.id=o.city_id LEFT JOIN states st ON st.id=o.state_id WHERE o.id=:owner AND o.user_id=:user AND o.deleted_at IS NULL");$q->execute(['owner'=>$id,'user'=>$c->authenticatedUserId]);return$q->fetch()?:[];}
 public function hours(PartnerContext$c):array{$q=$this->pdo->prepare("SELECT day_of_week,slot_order,is_closed,is_24_hours,is_overnight,opens_at,closes_at FROM partner_business_hours WHERE partner_id=:owner AND module_code=:module AND status='active' ORDER BY day_of_week,slot_order");$q->execute(['owner'=>$c->businessPartnerId,'module'=>$c->moduleCode]);return$q->fetchAll();}
 public function operations(PartnerContext$c):array{$q=$this->pdo->prepare("SELECT essivery_delivery,self_delivery,customer_pickup,service_at_customer_location FROM partner_fulfilment_settings WHERE partner_id=:owner AND module_code=:module AND status='active' LIMIT 1");$q->execute(['owner'=>$c->businessPartnerId,'module'=>$c->moduleCode]);return$q->fetch()?:[];}
 public function documents(PartnerContext$c):array{$table=$c->deliveryPartnerId!==null?'delivery_partner_documents':'partner_documents';$column=$c->deliveryPartnerId!==null?'delivery_partner_id':'partner_id';$owner=$c->deliveryPartnerId??$c->businessPartnerId;$q=$this->pdo->prepare("SELECT public_id,document_type,review_status,created_at FROM $table WHERE $column=:owner AND status='active' ORDER BY document_type");$q->execute(['owner'=>$owner]);return$q->fetchAll();}
 public function bank(PartnerContext$c):array{$table=$c->deliveryPartnerId!==null?'delivery_partner_bank_accounts':'partner_bank_accounts';$column=$c->deliveryPartnerId!==null?'delivery_partner_id':'partner_id';$owner=$c->deliveryPartnerId??$c->businessPartnerId;$q=$this->pdo->prepare("SELECT account_holder_name,account_number_last4,ifsc_code,review_status FROM $table WHERE $column=:owner AND status='active' LIMIT 1");$q->execute(['owner'=>$owner]);return$q->fetch()?:[];}
 public function module(PartnerContext$c):array{if($c->moduleCode==='RETAIL'){$q=$this->pdo->prepare("SELECT pc.name category_name,m.catalogue_setup_mode setup_mode,m.retail_confirmed_at confirmed_at FROM partner_retail_parent_categories m JOIN parent_categories pc ON pc.id=m.parent_category_id WHERE m.partner_id=:owner AND m.parent_category_id=:category AND m.status='active'");$q->execute(['owner'=>$c->businessPartnerId,'category'=>$c->parentCategoryId]);return$q->fetch()?:[];}if($c->moduleCode==='RESTAURANT'){$q=$this->pdo->prepare("SELECT r.id,r.menu_setup_mode setup_mode,r.setup_confirmed_at confirmed_at FROM restaurants r WHERE r.owner_user_id=:user AND r.deleted_at IS NULL LIMIT 1");$q->execute(['user'=>$c->authenticatedUserId]);$row=$q->fetch()?:[];$row['items']=[];if(!empty($row['id'])){$x=$this->pdo->prepare("SELECT c.name FROM restaurant_cuisines rc JOIN cuisines c ON c.id=rc.cuisine_id WHERE rc.restaurant_id=:id AND rc.status='active' ORDER BY c.name");$x->execute(['id'=>$row['id']]);$row['items']=array_column($x->fetchAll(),'name');}unset($row['id']);return$row;}if($c->moduleCode==='HOME_SERVICE'){$q=$this->pdo->prepare("SELECT h.id,h.setup_preference setup_mode,h.setup_confirmed_at confirmed_at FROM home_service_provider_profiles h WHERE h.partner_id=:owner LIMIT 1");$q->execute(['owner'=>$c->businessPartnerId]);$row=$q->fetch()?:[];$row['items']=[];if(!empty($row['id'])){$x=$this->pdo->prepare("SELECT m.name FROM home_service_provider_setup_services x JOIN home_service_masters m ON m.id=x.service_id WHERE x.provider_id=:id ORDER BY m.name");$x->execute(['id'=>$row['id']]);$row['items']=array_column($x->fetchAll(),'name');}unset($row['id']);return$row;}$q=$this->pdo->prepare("SELECT t.name vehicle_name,v.registration_number,v.vehicle_number,v.vehicle_ownership,v.setup_confirmed_at confirmed_at FROM delivery_partner_vehicles v JOIN delivery_vehicle_types t ON t.code=v.vehicle_type WHERE v.delivery_partner_id=:owner AND v.is_primary=1 AND v.status='active' LIMIT 1");$q->execute(['owner'=>$c->deliveryPartnerId]);return$q->fetch()?:[];}
 public function submit(PartnerContext$c,array$app,string$type):void{$this->pdo->prepare("UPDATE partner_onboarding_applications SET application_status='submitted',submitted_at=COALESCE(submitted_at,CURRENT_TIMESTAMP),current_step=NULL,last_saved_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['id'=>$app['id']]);$table=$c->deliveryPartnerId!==null?'delivery_partners':'partners';$owner=$c->deliveryPartnerId??$c->businessPartnerId;$this->pdo->prepare("UPDATE $table SET onboarding_status='submitted',updated_at=CURRENT_TIMESTAMP WHERE id=:owner")->execute(['owner'=>$owner]);$this->pdo->prepare("INSERT INTO partner_onboarding_status_history(public_id,application_id,from_status,to_status,transition_type,actor_type,actor_user_id) VALUES(:public,:application,:from,'submitted',:type,'partner',:user)")->execute(['public'=>Helpers::publicId('PSH'),'application'=>$app['id'],'from'=>$app['application_status'],'type'=>$type,'user'=>$c->authenticatedUserId]);}
}

