<?php
declare(strict_types=1);
namespace Essivery\Partner\Repositories;
use Essivery\Api\Core\ApiException;use Essivery\Partner\Domain\PartnerContext;use PDO;
final class PartnerDeliveryRepository
{
 private bool$checked=false;public function __construct(private PDO$pdo){}
 public function options():array{$this->schema();return$this->pdo->query("SELECT code,name,requires_registration,requires_driving_licence,requires_rc,insurance_required FROM delivery_vehicle_types WHERE status='active' ORDER BY display_order,name")->fetchAll();}
 public function option(string$code):array{$this->schema();$q=$this->pdo->prepare("SELECT code,name,requires_registration,requires_driving_licence,requires_rc,insurance_required FROM delivery_vehicle_types WHERE code=:code AND status='active' LIMIT 1");$q->execute(['code'=>$code]);return$q->fetch()?:[];}
 public function vehicle(PartnerContext$c,bool$lock=false):array{$this->schema();$suffix=$lock&&$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)!=='sqlite'?' FOR UPDATE':'';$q=$this->pdo->prepare("SELECT d.name,d.approval_status,d.availability_status,d.status partner_status,v.id vehicle_id,v.vehicle_type,COALESCE(v.registration_number,v.vehicle_number) registration_number,v.vehicle_ownership,v.setup_confirmed_at FROM delivery_partners d LEFT JOIN delivery_partner_vehicles v ON v.delivery_partner_id=d.id AND v.is_primary=1 AND v.status='active' WHERE d.id=:delivery AND d.user_id=:user AND d.deleted_at IS NULL LIMIT 1".$suffix);$q->execute(['delivery'=>$c->deliveryPartnerId,'user'=>$c->authenticatedUserId]);return$q->fetch()?:[];}
 public function save(PartnerContext$c,string$type,?string$registration,string$ownership,bool$confirmed):array{$row=$this->vehicle($c,true);$params=['delivery'=>$c->deliveryPartnerId,'type'=>$type,'registration'=>$registration,'ownership'=>$ownership,'confirmed'=>$confirmed?gmdate('Y-m-d H:i:s'):null];if(!empty($row['vehicle_id'])){$params['id']=$row['vehicle_id'];$this->pdo->prepare("UPDATE delivery_partner_vehicles SET vehicle_type=:type,vehicle_number=:registration,registration_number=:registration,vehicle_ownership=:ownership,setup_confirmed_at=:confirmed,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND delivery_partner_id=:delivery")->execute($params);}else{$this->pdo->prepare("INSERT INTO delivery_partner_vehicles(delivery_partner_id,vehicle_type,vehicle_number,registration_number,vehicle_ownership,setup_confirmed_at,is_primary,status) VALUES(:delivery,:type,:registration,:registration,:ownership,:confirmed,1,'active')")->execute($params);}return$this->vehicle($c,false);}
 private function schema():void{if($this->checked||$this->pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'){$this->checked=true;return;}$required=['delivery_partners'=>['id','user_id','name','approval_status','availability_status','status','deleted_at'],'delivery_partner_vehicles'=>['id','delivery_partner_id','vehicle_type','vehicle_number','registration_number','vehicle_ownership','setup_confirmed_at','is_primary','status','updated_at'],'delivery_vehicle_types'=>['code','name','requires_registration','requires_driving_licence','requires_rc','insurance_required','display_order','status']];$missing=[];foreach($required as$table=>$columns){$q=$this->pdo->prepare('SELECT column_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=:table');$q->execute(['table'=>$table]);foreach(array_diff($columns,array_column($q->fetchAll(),'column_name'))as$column)$missing[]="$table.$column";}if($missing)throw new ApiException(503,'PARTNER_DELIVERY_SCHEMA_UNAVAILABLE','The Phase 4F Delivery schema is incomplete.','Delivery Partner Setup is temporarily unavailable.',[],true,['missingColumns'=>$missing]);$this->checked=true;}
}
