<?php
declare(strict_types=1);
namespace Essivery\Partner\Repositories;
use Essivery\Api\Core\ApiException;use Essivery\Api\Core\Helpers;use Essivery\Partner\Domain\PartnerContext;use PDO;
final class PartnerRestaurantRepository
{
 private bool$checked=false;public function __construct(private PDO$p){}
 public function options():array{$this->schema();return$this->p->query("SELECT slug,name FROM cuisines WHERE status='active' ORDER BY name")->fetchAll();}
 public function profile(PartnerContext$c):array{$this->schema();$q=$this->p->prepare("SELECT p.business_name,r.id restaurant_id,r.menu_setup_mode,r.setup_confirmed_at FROM partners p LEFT JOIN restaurants r ON r.owner_user_id=p.user_id AND r.deleted_at IS NULL WHERE p.id=:partner AND p.user_id=:user AND p.deleted_at IS NULL LIMIT 1");$q->execute(['partner'=>$c->businessPartnerId,'user'=>$c->authenticatedUserId]);$row=$q->fetch()?:[];$row['cuisines']=[];if(!empty($row['restaurant_id'])){$q=$this->p->prepare("SELECT c.slug,c.name FROM restaurant_cuisines rc JOIN cuisines c ON c.id=rc.cuisine_id AND c.status='active' WHERE rc.restaurant_id=:restaurant AND rc.status='active' ORDER BY c.name");$q->execute(['restaurant'=>$row['restaurant_id']]);$row['cuisines']=$q->fetchAll();}return$row;}
 public function resolveCuisines(array$codes):array{$this->schema();$ph=implode(',',array_fill(0,count($codes),'?'));$q=$this->p->prepare("SELECT id,slug,name FROM cuisines WHERE status='active' AND slug IN($ph)");$q->execute($codes);return$q->fetchAll();}
 public function save(PartnerContext$c,string$mode,array$cuisines):void{$this->module($c);$q=$this->p->prepare("SELECT business_name,city_id FROM partners WHERE id=:partner AND user_id=:user AND deleted_at IS NULL LIMIT 1");$q->execute(['partner'=>$c->businessPartnerId,'user'=>$c->authenticatedUserId]);$owner=$q->fetch()?:[];if(empty($owner['city_id']))throw new ApiException(409,'RESTAURANT_LOCATION_REQUIRED','Restaurant location must be completed before Restaurant Setup.','Complete the Restaurant location first.');$public=Helpers::publicId('RST');$params=['public'=>$public,'user'=>$c->authenticatedUserId,'name'=>$owner['business_name'],'slug'=>'restaurant-'.strtolower($public),'city'=>$owner['city_id'],'mode'=>$mode];$sql=$this->p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'?"INSERT INTO restaurants(public_id,owner_user_id,name,slug,city_id,menu_setup_mode,setup_confirmed_at,status,operational_status) VALUES(:public,:user,:name,:slug,:city,:mode,CURRENT_TIMESTAMP,'inactive','closed') ON CONFLICT(owner_user_id) DO UPDATE SET menu_setup_mode=excluded.menu_setup_mode,setup_confirmed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP":"INSERT INTO restaurants(public_id,owner_user_id,name,slug,city_id,menu_setup_mode,setup_confirmed_at,status,operational_status) VALUES(:public,:user,:name,:slug,:city,:mode,CURRENT_TIMESTAMP(6),'inactive','closed') ON DUPLICATE KEY UPDATE menu_setup_mode=VALUES(menu_setup_mode),setup_confirmed_at=CURRENT_TIMESTAMP(6),updated_at=CURRENT_TIMESTAMP(6)";$this->p->prepare($sql)->execute($params);$q=$this->p->prepare("SELECT id FROM restaurants WHERE owner_user_id=:user AND deleted_at IS NULL LIMIT 1");$q->execute(['user'=>$c->authenticatedUserId]);$rid=(int)$q->fetchColumn();$this->p->prepare("UPDATE restaurant_cuisines SET status='inactive' WHERE restaurant_id=:restaurant AND status='active'")->execute(['restaurant'=>$rid]);foreach($cuisines as$x){$params=['restaurant'=>$rid,'cuisine'=>$x['id']];$sql=$this->p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'?"INSERT INTO restaurant_cuisines(restaurant_id,cuisine_id,status) VALUES(:restaurant,:cuisine,'active') ON CONFLICT(restaurant_id,cuisine_id) DO UPDATE SET status='active'":"INSERT INTO restaurant_cuisines(restaurant_id,cuisine_id,status) VALUES(:restaurant,:cuisine,'active') ON DUPLICATE KEY UPDATE status='active'";$this->p->prepare($sql)->execute($params);}}
 private function module(PartnerContext$c):void{$params=['public'=>Helpers::publicId('PBM'),'partner'=>$c->businessPartnerId,'module'=>'RESTAURANT'];$sql=$this->p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'?"INSERT INTO partner_business_modules(public_id,partner_id,module_code,status) VALUES(:public,:partner,:module,'active') ON CONFLICT(partner_id,module_code) DO UPDATE SET status='active',updated_at=CURRENT_TIMESTAMP":"INSERT INTO partner_business_modules(public_id,partner_id,module_code,status) VALUES(:public,:partner,:module,'active') ON DUPLICATE KEY UPDATE status='active',updated_at=CURRENT_TIMESTAMP(6)";$this->p->prepare($sql)->execute($params);}
 private function schema():void{if($this->checked||$this->p->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'){$this->checked=true;return;}$req=['restaurants'=>['id','public_id','owner_user_id','name','slug','city_id','operational_status','menu_setup_mode','setup_confirmed_at','status','deleted_at'],'restaurant_cuisines'=>['restaurant_id','cuisine_id','status'],'cuisines'=>['id','slug','name','status']];$m=[];foreach($req as$t=>$cs){$q=$this->p->prepare('SELECT column_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=:table');$q->execute(['table'=>$t]);foreach(array_diff($cs,array_column($q->fetchAll(),'column_name'))as$c)$m[]="$t.$c";}if($m)throw new ApiException(503,'PARTNER_RESTAURANT_SCHEMA_UNAVAILABLE','The Phase 4D Restaurant schema is incomplete.','Restaurant Setup is temporarily unavailable.',[],true,['missingColumns'=>$m]);$this->checked=true;}
}
